module.exports = {
    head1:{
        color:'#000',
        fontSize:30,
        textAlign:'center'
    },
    head2:{
        color:'#000',
        fontSize:17,
        textAlign:'center'
    },
    formgroup:{
        display:'flex',
        flexDirection:'column',
        width:'100%',
        marginVertical:10
      },
      label:{
        color:'#000',
        fontSize:17,
        marginLeft:10,
        marginBottom:10
      },
      input:{
        backgroundColor:'#939292',
        padding:10,
        borderRadius:20
      },
      link:{
        color:'#939292',
        textDecorationLine:'underline'
      },
      link2:{
        fontSize:17,
        textAlign:'center',
        marginVertical:10
      },
      errorMsg:{
        color:'white',
        backgroundColor:'red',
        padding:10,
        borderRadius:10
      },  
}